version: '3'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
      - apiservice

  apiservice:
    build:
      context: ./apiService
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - .env

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
