version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
      - apiService

  apiService:
    build:
      context: ./apiService
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - .env

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
